### ISSUE TITLE
Tests should return 0, not 1

### ISSUE THREAD

**Issue by ChristopherHogan** [hariharan-devarajan/basket#3]
Is there a reason why the `main` functions in `test/*.cpp` return 1 on success? A non-zero return value from `main` is usually meant to signify an error.

**Comment by Keith-Bateman** [comment]
I'll go one further and say that appropriate behavior in main is to call exit(EXIT_SUCCESS) on program termination rather than using an arbitrary return value, but no I don't think there's special meaning here. I was working on the test cases anyway, so I'll take a look at them when I can get to a computer.

**Comment by Keith-Bateman** [comment]
This is fixed in latest release (0.0.3)
